"""HTML email renderer: converts EmailDraft Pydantic models into professional HTML emails.

Uses Jinja2 with inline CSS for maximum email client compatibility.
Generates standalone HTML files that can be previewed in any browser
or sent via Amazon SES/SMTP.

Security: Jinja2 autoescape is enabled (select_autoescape) to prevent XSS in
generated HTML. All template variables are escaped by default. Callers should
validate prospect data before rendering. For production Amazon SES delivery,
add CAN-SPAM compliance elements (unsubscribe link, physical address).

Compliance footer: set COMPLIANCE_FOOTER_REQUIRED=true to append an unsubscribe
link and physical address to every rendered email (CAN-SPAM / CASL compliance).
Default is off to preserve exact blog behavior.
"""

import json
import logging
import os
from datetime import datetime, timezone

from strands import tool

logger = logging.getLogger(__name__)

# Cached compiled Jinja2 template: created once on first render, reused thereafter.
_cached_template = None

# Placeholder physical address used in the compliance footer when COMPLIANCE_FOOTER_REQUIRED is set.
# Replace with a real address before production use.
_COMPLIANCE_PHYSICAL_ADDRESS = "AnyCompany, 123 Main St, Seattle, WA 98101, USA"

# Inline HTML email template (no external file dependency for Amazon Bedrock AgentCore deployment)
EMAIL_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ subject }}</title>
</head>
<body style="margin:0;padding:0;background-color:#f4f4f7;\
font-family:-apple-system,BlinkMacSystemFont,\
'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" \
style="background-color:#f4f4f7;padding:40px 20px;">
<tr><td align="center">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" \
style="background-color:#ffffff;border-radius:8px;\
overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">

<!-- Header -->
<tr><td style="background:linear-gradient(135deg,#1a1a2e 0%,#16213e 100%);\
padding:32px 40px;">
<h1 style="margin:0;color:#ffffff;font-size:18px;\
font-weight:600;letter-spacing:-0.3px;">{{ brand_name }}</h1>
<p style="margin:4px 0 0;color:#a0aec0;font-size:12px;">\
Social Intelligence Outreach</p>
</td></tr>

<!-- Subject line -->
<tr><td style="padding:32px 40px 0;">
<p style="margin:0;color:#718096;font-size:11px;\
text-transform:uppercase;letter-spacing:1px;\
font-weight:600;">Subject</p>
<h2 style="margin:8px 0 0;color:#1a202c;font-size:20px;\
font-weight:600;line-height:1.3;">{{ subject }}</h2>
</td></tr>

<!-- Divider -->
<tr><td style="padding:20px 40px 0;">\
<hr style="border:none;border-top:1px solid #e2e8f0;margin:0;"></td></tr>

<!-- Body -->
<tr><td style="padding:24px 40px;">
<div style="color:#2d3748;font-size:15px;line-height:1.7;">
{% for paragraph in body_paragraphs %}
<p style="margin:0 0 16px;">{{ paragraph }}</p>
{% endfor %}
</div>
</td></tr>

<!-- Personalization tokens -->
{% if personalization_tokens %}
<tr><td style="padding:0 40px 24px;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" \
style="background-color:#f7fafc;border-radius:6px;\
border:1px solid #e2e8f0;">
<tr><td style="padding:16px 20px;">
<p style="margin:0 0 8px;color:#718096;font-size:11px;\
text-transform:uppercase;letter-spacing:1px;\
font-weight:600;">Data Points Referenced</p>
{% for token in personalization_tokens %}
<span style="display:inline-block;background-color:#edf2f7;\
color:#4a5568;font-size:12px;padding:4px 10px;\
border-radius:12px;margin:2px 4px 2px 0;">{{ token }}</span>
{% endfor %}
</td></tr>
</table>
</td></tr>
{% endif %}

<!-- Score badge -->
{% if score > 0 %}
<tr><td style="padding:0 40px 24px;">
<table role="presentation" cellpadding="0" cellspacing="0">
<tr>
<td style="background-color:{{ score_color | e }};\
color:#ffffff;font-size:13px;font-weight:600;\
padding:6px 14px;border-radius:12px;">
Score: {{ score }}/100 &middot; Confidence: {{ confidence }}
</td>
<td style="padding-left:8px;">
<span style="color:#718096;font-size:12px;">\
{{ data_quality }} quality</span>
</td>
</tr>
</table>
</td></tr>
{% endif %}

<!-- Footer -->
<tr><td style="background-color:#f7fafc;padding:24px 40px;\
border-top:1px solid #e2e8f0;">
<p style="margin:0;color:#a0aec0;font-size:11px;">
Generated by AnyCompany Social Intelligence \
&middot; {{ generated_at }}<br>
Prospect ID: {{ prospect_id }} \
&middot; {{ brand_compliant_text }}
</p>
{% if compliance_footer %}
<p style="margin:12px 0 0;color:#a0aec0;font-size:10px;border-top:1px solid #e2e8f0;padding-top:12px;">
<a href="{{ unsubscribe_url | e }}" style="color:#718096;">Unsubscribe</a>
&nbsp;&middot;&nbsp;{{ physical_address }}
</p>
{% endif %}
</td></tr>

</table>
</td></tr>
</table>
</body>
</html>"""


def render_email_html(
    prospect_id: str,
    subject: str,
    body: str,
    personalization_tokens: list[str] | None = None,
    brand_compliant: bool = True,
    score: int = 0,
    confidence: float = 0.0,
    data_quality: str = "medium",
    brand_name: str = "AnyCompany",
) -> str:
    """Render an EmailDraft into a professional HTML email.

    Use this after the email generation agent produces an EmailDraft to create
    a polished, email-client-compatible HTML version. The output can be previewed
    in a browser or sent via Amazon SES.

    Args:
        prospect_id: Prospect identifier.
        subject: Email subject line.
        body: Email body text (plain text, will be split into paragraphs).
        personalization_tokens: Data points referenced in the email.
        brand_compliant: Whether the email passed brand guidelines.
        score: Prospect relevance score (0-100).
        confidence: Score confidence (0.0-1.0).
        data_quality: Data quality assessment.
        brand_name: Brand name for the header.
    """
    from jinja2 import Environment, select_autoescape

    # Module-level cache for the compiled template (created once, reused)
    global _cached_template  # noqa: PLW0603
    if _cached_template is None:
        # nosemgrep: python.flask.security.xss.audit.direct-use-of-jinja2
        # autoescape is explicitly enabled below, so HTML escaping is NOT bypassed.
        # This renders a self-contained email template (not a Flask response), so
        # render_template() does not apply. False positive; escaping is verified on.
        env = Environment(
            autoescape=select_autoescape(default_for_string=True, default=True),
        )
        _cached_template = env.from_string(EMAIL_TEMPLATE)

    # Split body into paragraphs
    body_paragraphs = [p.strip() for p in body.split("\n") if p.strip()]

    # Score color
    if score >= 80:
        score_color = "#38a169"  # green
    elif score >= 60:
        score_color = "#d69e2e"  # yellow
    else:
        score_color = "#e53e3e"  # red

    template = _cached_template
    compliance_footer = bool(os.environ.get("COMPLIANCE_FOOTER_REQUIRED", ""))
    unsubscribe_url = os.environ.get("UNSUBSCRIBE_URL", "https://example.com/unsubscribe")

    html = template.render(
        brand_name=brand_name,
        subject=subject,
        body_paragraphs=body_paragraphs,
        personalization_tokens=personalization_tokens or [],
        score=score,
        score_color=score_color,
        confidence=f"{confidence:.0%}" if confidence else "N/A",
        data_quality=data_quality,
        prospect_id=prospect_id,
        brand_compliant_text="Brand compliant" if brand_compliant else "Needs review",
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        compliance_footer=compliance_footer,
        unsubscribe_url=unsubscribe_url,
        physical_address=_COMPLIANCE_PHYSICAL_ADDRESS,
    )

    return json.dumps(
        {
            "html": html,
            "prospect_id": prospect_id,
            "subject": subject,
            "rendered": True,
        }
    )


@tool
def render_email_html_tool(
    prospect_id: str,
    subject: str,
    body: str,
    personalization_tokens: list[str] | None = None,
    score: int = 0,
    confidence: float = 0.0,
    data_quality: str = "medium",
) -> str:
    """Render an email draft into professional HTML for preview or Amazon SES delivery.

    Args:
        prospect_id: Prospect identifier.
        subject: Email subject line.
        body: Email body text (paragraphs separated by newlines).
        personalization_tokens: Ordered data points referenced in the email.
        score: Prospect relevance score (0-100).
        confidence: Score confidence (0.0-1.0).
        data_quality: Data quality assessment (high/medium/low).
    """
    if isinstance(personalization_tokens, str):
        tokens = [token.strip() for token in personalization_tokens.split(",") if token.strip()]
    else:
        tokens = [str(token).strip() for token in personalization_tokens or [] if str(token).strip()]
    return render_email_html(
        prospect_id=prospect_id,
        subject=subject,
        body=body,
        personalization_tokens=tokens,
        score=score,
        confidence=confidence,
        data_quality=data_quality,
    )
